CREATE TABLE Athlete
(
	aID     INTEGER 	 NOT NULL,
	name 	VARCHAR (15) NOT NULL,
	country VARCHAR (50) NOT NULL,
	age     SMALLINT NOT NULL,

	CONSTRAINT  athConPK 	PRIMARY KEY (aID)
);

CREATE TABLE Event
(
	eID 	INTEGER 	 NOT NULL,
	name 	VARCHAR(50)  NOT NULL,
	date 	DATE 		 NOT NULL,
	venue	VARCHAR(100) NOT NULL,
	time 	TIME 		 NOT NULL,

	CONSTRAINT	eveConPK 	PRIMARY KEY (eID)
);

CREATE TABLE Participate
(
 aID INTEGER NOT NULL,
 eID INTEGER NOT NULL,
 CONSTRAINT participatePK PRIMARY KEY(aID, eID),
 CONSTRAINT pFK FOREIGN KEY (aID) REFERENCES Athlete (aID),
 CONSTRAINT p2FK FOREIGN KEY (eID) REFERENCES Event (eID)
);

CREATE TABLE Medals
(
 aID INTEGER NOT NULL,
 eID INTEGER NOT NULL,
 medals VARCHAR (20) NOT NULL, 
 --medals can be "First", "Second", "Third"
 CONSTRAINT medalPK PRIMARY KEY(aID, eID),
 CONSTRAINT mFK FOREIGN KEY (aID) REFERENCES Athlete (aID),
 CONSTRAINT m2FK FOREIGN KEY (eID) REFERENCES Event (eID)
);
